---
development:
  cloud_name: hydrtfmgb
  api_key: '654444392283723'
  api_secret: QmCt6kEnTl4TKtRyXM8X2A5eXg0
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hydrtfmgb
  api_key: '654444392283723'
  api_secret: QmCt6kEnTl4TKtRyXM8X2A5eXg0
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hydrtfmgb
  api_key: '654444392283723'
  api_secret: QmCt6kEnTl4TKtRyXM8X2A5eXg0
  enhance_image_tag: true
  static_image_support: false
