development:
  adapter: postgresql
  encoding: unicode
  database: smw_development
  host: localhost
  pool: 5
  username: tjl
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: smw_test
  host: localhost
  pool: 5
  username: tjl
  password:
