development:
  adapter: postgresql
  encoding: unicode
  database: shelterme
  host: localhost
  pool: 5
  username: tjl
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: test_shelterme
  host: localhost
  pool: 5
  username: tjl
  password:
    